name: Install Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo apt-get update 
        sudo apt-get install -y docker.io 

    - name: Start Docker
      run: |
        sudo systemctl enable docker 
        sudo systemctl start docker   

    - name: Check Docker version
      run: |
        docker --version  
        sudo docker run hello-world 

    - name: Check if Docker is active
      run: |
        sudo systemctl is-active docker
