name: Erste Workflow
on:
  push:
    branches:
      - production
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        env:
            NAME: "Enes"
        run: |
            echo "Hello World"
            echo ${{ env.NAME }}
