name: Auto-Check Workflow 

on:
    workflow_dispatch:

jobs:
  CheckEngine:
    runs-on: ubuntu-latest

    steps:
    # Repository klonen
    - name: Clone Repository
      run: git clone https://github.com/enesmat/githubgarage.git

    # Shell-Skript ausführen
    - name: Run script.sh
      run: |
        chmod +x script.sh
        .github/workflows/script.sh